from onemodel.sbml2dae.dae_model import DaeModel, StateType

class Matlab:
    """ Takes a DAE model as input and exports a matlab implementation.
    """
    def __init__(self, dae, output_path):
        """ Inits Matlab.
        """
        self.dae = dae
        self.output_path = output_path

    def writeWarning(self, f):
        f.write(f'% This file was automatically generated by onemodel.\n')
        f.write(
            f'% Any changes you make to it will be overwritten the next time\n'
        )
        f.write(f'% the file is generated.\n\n')

    def exportDefaultParameters(self):
        """ Generate Matlab function which returns the default parameters.
        """

        filepath = self.output_path
        filepath += '/'
        filepath += self.dae.getModelName()
        filepath += '_param.m'

        # Create and open the file to export.
        f = open(filepath, "w")

        # Function header.
        f.write(f'function [p,x0,M] = {self.dae.getModelName()}_param()\n')
        self.writeWarning(f)

        # Default parameters.
        f.write(f'% Default parameters value.\n')
        for item in self.dae.getParameters():
            f.write(f'p.{item["id"]} = {item["value"]};\n')

        ## Default initial conditions.
        f.write(f'\n% Default initial conditions.\n')
        f.write(f'x0 = [\n')
        for item in self.dae.getStates():
            if item['type'] == StateType.ODE:
                f.write(
                    f'\t{item["initialCondition"]} % {item["id"]}\n'
                )
            elif item['type'] == StateType.ALGEBRAIC:
                f.write(
                    f'\t{item["initialCondition"]} % {item["id"]} (algebraic)\n'
                )
        f.write(f'];\n')

        # Mass matrix.
        f.write(f'\n% Mass matrix for algebraic simulations.\n')
        f.write(f'M = [\n')
        M = []
        for item in self.dae.getStates():
            if item['type'] == StateType.ODE:
                M.append(1)
            elif item['type'] == StateType.ALGEBRAIC:
                M.append(0)

        i = 0
        i_max = len(M)
        while i < i_max:
            f.write('\t')
            f.write('0 '*i)
            f.write(f'{M[i]} ')
            f.write('0 '*(i_max-i-1))
            f.write('\n')
            i += 1

        f.write(f'];\n')

        f.write(f'\nend\n')

        f.close()

        return filepath


                
if __name__ == '__main__':
    dae = DaeModel(
        '/home/nobel/Sync/python/workspace/onemodel/examples/antithetic.xml'
    )

    matlab = Matlab(
        dae,
        '/home/nobel/Sync/python/workspace/onemodel/examples/build'
    )

    matlab.exportDefaultParameters()

