@@grammar::CALC
@@eol_comments:: /#.*?$/

start = expression $ ;

expression =
  | parameter
  | number
  | string
  | identifier
  ;

parameter = name:identifier '=' '{' value:number ',' units:string '}' [comment:string] ;

@name
identifier = /(?!\d)\w+/ ;

# Definition of numbers, e.g.: '1', '1.0', '1e-1'.
number = /\d+(?:\.\d+)?(?:e(?:\+|\-)\d+)?/ ;

# Definition of strings (they can be formed with ' and ").
string = 
  | /"(.*?)"/
  | /'(.*?)'/
  ;
