classdef ex01_simple_gene_expression
	% This file was automatically generated by OneModel.
	% Any changes you make to it will be overwritten the next time
	% the file is generated.

	properties
		p      % Default model parameters.
		x0     % Default initial conditions.
		M      % Mass matrix for DAE systems.
		opts   % Simulation options.
	end

	methods
		function obj = ex01_simple_gene_expression()
			%% Constructor of ex01_simple_gene_expression.
			obj.p    = obj.default_parameters();
			obj.x0   = obj.initial_conditions();
			obj.M    = obj.mass_matrix();
			obj.opts = obj.simulation_options();
		end

		function p = default_parameters(~)
			%% Default parameters value.
			p = [];
			p.k_m = 1.0;
			p.d_m = 1.0;
			p.k_p = 1.0;
			p.d_p = 1.0;
		end

		function x0 = initial_conditions(~)
			%% Default initial conditions.
			x0 = [
				0.0 % mRNA
				0.0 % protein
			];
		end

		function M = mass_matrix(~)
			%% Mass matrix for DAE systems.
			M = [
				1 0 
				0 1 
			];
		end

		function opts = simulation_options(~)
			%% Default simulation options.
			opts.t_end = 10.0;
			opts.t_init = 0.0;
		end

		function dx = ode(~,t,x,p)
			%% Evaluate the ODE.
			%
			% Args:
			%	 t Current time in the simulation.
			%	 x Array with the state value.
			%	 p Struct with the parameters.
			%
			% Return:
			%	 dx Array with the ODE.

			% ODE and algebraic states:
			mRNA = x(1,:);
			protein = x(2,:);

			% Assigment states:

			% der(mRNA)
			dx(1,1) =  + (p.k_m) - (p.d_m.*mRNA) + (p.k_p.*mRNA) - (p.k_p.*mRNA);

			% der(protein)
			dx(2,1) =  + (p.k_p.*mRNA) - (p.d_p.*protein);

		end
		function out = simout2struct(~,t,x,p)
			%% Convert the simulation output into an easy-to-use struct.

			% We need to transpose state matrix.
			x = x';
			% ODE and algebraic states:
			mRNA = x(1,:);
			protein = x(2,:);

			% Assigment states:

			% Save simulation time.
			out.t = t;

			% Vector for extending single-value states and parameters.
			ones_t = ones(size(t'));


			% Save states.
			out.mRNA = (mRNA.*ones_t)';
			out.protein = (protein.*ones_t)';

			% Save parameters.
			out.k_m = (p.k_m.*ones_t)';
			out.d_m = (p.d_m.*ones_t)';
			out.k_p = (p.k_p.*ones_t)';
			out.d_p = (p.d_p.*ones_t)';

		end
		function plot(~,out)
			%% Plot simulation result.
			figure('Name','');
			subplot(2,1,1);
			plot(out.t, out.mRNA);
			title("mRNA");
			ylim([0, +inf]);
			grid on;

			subplot(2,1,2);
			plot(out.t, out.protein);
			title("protein");
			ylim([0, +inf]);
			grid on;

		end
	end
end
